import{a as l,i as u,S as m}from"./assets/vendor-91c99ba8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();l.defaults.headers.common["x-api-key"]="live_v5ZqsoCBTNbnAMj0I30H5oO7TBEyyAOAqsK6dL1nSDQ8kYLpTDBJqJJ1Cj2BM2Al";function y(){return l.get("https://api.thecatapi.com/v1/breeds").then(({data:e})=>e)}function h(e){return l.get("https://api.thecatapi.com/v1/images/search",{breed_ids:e}).then(({data:s})=>s)}const d=document.querySelector(".select-block .loader"),c=document.querySelector(".info-block .loader"),f=document.querySelector(".info-container"),p=document.querySelector("#select"),a=[];d.style.display="block";c.style.display="none";p.classList.add("hidden");y().then(e=>{g(e)}).catch(e=>{u.error({title:"Error",message:e.message}),d.style.display="none"});function g(e){d.style.display="none",p.classList.remove("hidden"),a.push(...e);const s=a.map(n=>({text:n.name,value:n.id}));new m({select:"#select",data:s,events:{afterChange:v}})}function v(e){const s=a.find(n=>n.id===e[0].value);c.style.display="block",f.innerHTML="",h(s.id).then(n=>{const r=L(s,n[0]);f.innerHTML=r}).catch(n=>{u.error({title:"Error",message:n.message})}).finally(()=>{c.style.display="none"})}function L(e,s){return`
    <div class="cat-info-wrapper">
      <img class="cat-info-img" src="${s.url}" alt="${e.name}">
      <div class="cat-info-details">
        <h3 class="cat-info-title">${e.name}</h3>
        <p class="cat-info-text">${e.description}</p>
        <p class="cat-info-text"><strong>Temperament:</strong> ${e.temperament}</p>
      </div>
    </div>
  `}
//# sourceMappingURL=commonHelpers.js.map
